version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python manage.py db init && python manage.py db migrate && python manage.py run"
    volumes:
      - ./src:/app/src
    ports:
      - "5000:5000"
